"""Curated MCP catalog — ground truth for Phase 1+ installs (not a hardcoded adapter table).

Each entry describes how Hermes discovers/installs the server. Runtime still uses the
Documentation Reader + Installation Engine; this seed is the registry feed (§4.2).
"""

from __future__ import annotations

CATALOG: list[dict] = [
    {
        "name": "Filesystem",
        "slug": "filesystem",
        "description": "Secure file operations with configurable access controls. Read, write, and list directories.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-filesystem",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-filesystem",
            "npx": "npx -y @modelcontextprotocol/server-filesystem",
            "source_subdir": "src/filesystem",
        },
        "tags": ["filesystem", "files", "official"],
        "auth_type": "none",
        "required_env": [],
        "start_args_template": ["{{ALLOW_PATH}}"],
        "tools_hint": ["read_file", "write_file", "list_directory", "search_files"],
    },
    {
        "name": "GitHub",
        "slug": "github",
        "description": "Repository management, issues, PRs, and code search via the GitHub API.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-github",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-github",
            "npx": "npx -y @modelcontextprotocol/server-github",
            "source_subdir": "src/github",
        },
        "tags": ["github", "git", "issues", "official"],
        "auth_type": "pat",
        "required_env": [
            {"name": "GITHUB_PERSONAL_ACCESS_TOKEN", "purpose": "GitHub PAT", "secret": True}
        ],
        "tools_hint": ["create_issue", "list_commits", "search_code", "create_pull_request"],
    },
    {
        "name": "Memory",
        "slug": "memory",
        "description": "Knowledge graph-based persistent memory for agents across sessions.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-memory",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-memory",
            "npx": "npx -y @modelcontextprotocol/server-memory",
            "source_subdir": "src/memory",
        },
        "tags": ["memory", "knowledge-graph", "official"],
        "auth_type": "none",
        "required_env": [],
        "tools_hint": ["create_entities", "create_relations", "search_nodes", "open_nodes"],
    },
    {
        "name": "Fetch",
        "slug": "fetch",
        "description": "Web content fetching and conversion for LLM consumption.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-fetch",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-fetch",
            "npx": "npx -y @modelcontextprotocol/server-fetch",
            "python": "mcp-server-fetch",
            "source_subdir": "src/fetch",
        },
        "tags": ["http", "web", "fetch", "official"],
        "auth_type": "none",
        "required_env": [],
        "tools_hint": ["fetch"],
    },
    {
        "name": "PostgreSQL",
        "slug": "postgres",
        "description": "Read-only SQL access to PostgreSQL databases with schema inspection.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-postgres",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-postgres",
            "npx": "npx -y @modelcontextprotocol/server-postgres",
            "source_subdir": "src/postgres",
        },
        "tags": ["postgres", "sql", "database", "official"],
        "auth_type": "api_key",
        "required_env": [
            {"name": "POSTGRES_CONNECTION_STRING", "purpose": "Postgres connection URI", "secret": True}
        ],
        "start_args_template": ["{{POSTGRES_CONNECTION_STRING}}"],
        "tools_hint": ["query"],
    },
    {
        "name": "SQLite",
        "slug": "sqlite",
        "description": "Database interaction and business intelligence over SQLite files.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-sqlite",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-sqlite",
            "npx": "npx -y @modelcontextprotocol/server-sqlite",
            "source_subdir": "src/sqlite",
        },
        "tags": ["sqlite", "database", "official"],
        "auth_type": "none",
        "required_env": [
            {"name": "SQLITE_DB_PATH", "purpose": "Path to .sqlite database file", "secret": False}
        ],
        "tools_hint": ["read_query", "write_query", "list_tables", "describe_table"],
    },
    {
        "name": "Brave Search",
        "slug": "brave-search",
        "description": "Web and local search using Brave's Search API.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-brave-search",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-brave-search",
            "npx": "npx -y @modelcontextprotocol/server-brave-search",
            "source_subdir": "src/brave-search",
        },
        "tags": ["search", "brave", "web", "official"],
        "auth_type": "api_key",
        "required_env": [
            {"name": "BRAVE_API_KEY", "purpose": "Brave Search API key", "secret": True}
        ],
        "tools_hint": ["brave_web_search", "brave_local_search"],
    },
    {
        "name": "Puppeteer",
        "slug": "puppeteer",
        "description": "Browser automation and web scraping via Puppeteer.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-puppeteer",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-puppeteer",
            "npx": "npx -y @modelcontextprotocol/server-puppeteer",
            "source_subdir": "src/puppeteer",
        },
        "tags": ["browser", "scraping", "puppeteer", "official"],
        "auth_type": "none",
        "required_env": [],
        "tools_hint": ["puppeteer_navigate", "puppeteer_screenshot", "puppeteer_click"],
    },
    {
        "name": "Slack",
        "slug": "slack",
        "description": "Channel management and messaging integration for Slack workspaces.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-slack",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-slack",
            "npx": "npx -y @modelcontextprotocol/server-slack",
            "source_subdir": "src/slack",
        },
        "tags": ["slack", "chat", "official"],
        "auth_type": "api_key",
        "required_env": [
            {"name": "SLACK_BOT_TOKEN", "purpose": "Slack bot token (xoxb-…)", "secret": True},
            {"name": "SLACK_TEAM_ID", "purpose": "Slack team / workspace ID", "secret": False},
        ],
        "tools_hint": ["slack_list_channels", "slack_post_message", "slack_reply_to_thread"],
    },
    {
        "name": "Google Maps",
        "slug": "google-maps",
        "description": "Location services, directions, and place details via Google Maps.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-google-maps",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-google-maps",
            "npx": "npx -y @modelcontextprotocol/server-google-maps",
            "source_subdir": "src/google-maps",
        },
        "tags": ["maps", "geo", "official"],
        "auth_type": "api_key",
        "required_env": [
            {"name": "GOOGLE_MAPS_API_KEY", "purpose": "Google Maps API key", "secret": True}
        ],
        "tools_hint": ["maps_geocode", "maps_search_places", "maps_place_details"],
    },
    {
        "name": "Git",
        "slug": "git",
        "description": "Tools to read, search, and manipulate Git repositories.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-git",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-git",
            "python": "mcp-server-git",
            "source_subdir": "src/git",
        },
        "tags": ["git", "vcs", "official"],
        "auth_type": "none",
        "required_env": [],
        "tools_hint": ["git_status", "git_log", "git_diff", "git_show"],
    },
    {
        "name": "Everything",
        "slug": "everything",
        "description": "Reference / test MCP server exercising prompts, resources, and tools.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-everything",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-everything",
            "npx": "npx -y @modelcontextprotocol/server-everything",
            "source_subdir": "src/everything",
        },
        "tags": ["reference", "test", "official"],
        "auth_type": "none",
        "required_env": [],
        "tools_hint": ["echo", "add", "printEnv"],
    },
    {
        "name": "Sequential Thinking",
        "slug": "sequential-thinking",
        "description": "Dynamic problem-solving through thought sequences.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://www.npmjs.com/package/@modelcontextprotocol/server-sequential-thinking",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "npm": "@modelcontextprotocol/server-sequential-thinking",
            "npx": "npx -y @modelcontextprotocol/server-sequential-thinking",
            "source_subdir": "src/sequentialthinking",
        },
        "tags": ["reasoning", "official"],
        "auth_type": "none",
        "required_env": [],
        "tools_hint": ["sequentialthinking"],
    },
    {
        "name": "Time",
        "slug": "time",
        "description": "Time and timezone conversion capabilities.",
        "repo_url": "https://github.com/modelcontextprotocol/servers",
        "package_url": "https://pypi.org/project/mcp-server-time/",
        "author": "Anthropic / MCP",
        "classification": "official",
        "latest_version": "latest",
        "install_methods": {
            "python": "mcp-server-time",
            "uvx": "uvx mcp-server-time",
            "source_subdir": "src/time",
        },
        "tags": ["time", "timezone", "official"],
        "auth_type": "none",
        "required_env": [],
        "tools_hint": ["get_current_time", "convert_time"],
    },
]
